### ISSUE TITLE
Grounds Blogs

### ISSUE THREAD

**Issue by originalhat** [originalhat/blog.old#3]
## Purpose

> I'd like to have a blog that's specific to the progress to of "Grounds" as we move along. That we can openly discuss what sort of problems we've been running into, when we expect things to be finished, announce new features and in general hold ourselves accountable to our shareholders ("customers").
> 
> We can hopefully gain some PR, especially in the technical and startup community for our efforts. Always a good thing - we might also be able to facilitate some useful feedback every now and again too.
> 
> Another key reason we should have this content is for a point of reference when people ask, because they will. An "About Us" page, that gives us the info about our product, company and leadership paired with an up to date blog will give anyone interested in what we're attempting to do (including ourselves), a clear place to look.
> 
> Think of it as a live manifesto to which we can adhere.
## Content

I'd like to initially go with a very basic CMS that loads either a plain text or YAML file for blog content. Once placed in the directory, Rails will AutoMagically™ serve the page to the desired location.

For example, the a YAML file would look something like:

``` yaml
post:
  title:  Bacon and Coffee
  date:   September 19th 2013
  author: Devin Brown
  body: |
    Black broken back bros bombastically breed bread baked 
    from bacon. Crunchy crisp cats cook cauldrons 
    of Californian candied cod...
```

This static content could be loaded from the `public/blog/posts/` directory, and would then be entered into the database via a loading script. The post would then be served from the populated database.
### Required Fields
1. ID
2. TITLE
3. DATE
4. AUTHOR
5. BODY
## Mockup

Missing from mocks:
- share with Twitter
- share with Facebook
### Mobile

![blog-mobile-mock](https://raw.github.com/devinbrown/grounds/master/public/mocks/blog-mobile.png?login=devinbrown&token=e480df5f5c75b41299b8023e18afea91)
### Desktop

![blog-mock](https://raw.github.com/devinbrown/grounds/master/public/mocks/blog.png?login=devinbrown&token=20d2724fa508a173cb5d6bfb91773b0a)
## Color Swatches

Just a few options...
1. [Coffee](https://kuler.adobe.com/Coffee-color-theme-210291/)
   
   ![screen shot 2013-09-19 at 6 34 47 am](https://f.cloud.github.com/assets/579630/1172668/02f2f532-2128-11e3-9f5d-0af58bdb8e88.png)
2. [Coffee Set](https://kuler.adobe.com/Coffee-Set-color-theme-260198/)
   
   ![screen shot 2013-09-19 at 6 35 00 am](https://f.cloud.github.com/assets/579630/1172670/0889a6ee-2128-11e3-99de-1c9943ff47ca.png)
3. [coffee01](https://kuler.adobe.com/coffee01-color-theme-1008237/) - :heart: 
   
   ![screen shot 2013-09-19 at 6 35 07 am](https://f.cloud.github.com/assets/579630/1172671/0c739648-2128-11e3-91d3-ee0c90f5474a.png)
4. [Expresso](https://kuler.adobe.com/Expresso-color-theme-1340011/)
   
   ![screen shot 2013-09-19 at 6 35 14 am](https://f.cloud.github.com/assets/579630/1172673/116cb13e-2128-11e3-9dba-a26ec27769d5.png)

**Comment by ElijahGartin** [comment]
Are these pages that need to be built?

**Comment by originalhat** [comment]
@EGartin FUCK YES MY SHALOM BROTHER!

I'd like to have a blog that's specific to the progress to of "Grounds" as we move along. That we can openly discuss what sort of problems we've been running into, when we expect things to be finished, announce new features and in general hold ourselves accountable to our shareholders ("customers"). 

We can hopefully gain some PR, especially in the technical and startup community for our efforts. Always a good thing - we might also be able to facilitate some useful feedback every now and again too.

Another key reason we should have this content is for a point of reference when people ask, because they will. An "About Us" page, that gives us the info about our product, company and leadership paired with an up to date blog will give anyone interested in what we're attempting to do (including ourselves), a clear place to look. 

Think of it as a live manifesto to which we can adhere.

**Comment by originalhat** [comment]
PS - Both these issues #3, #4 will have comprehensive product documentation before anything is physically built.

**Comment by originalhat** [comment]
It was also be a fair guess that there will be more than just these two pages, but they're really just a starting point, based on priority imo.

**Comment by originalhat** [comment]
For Motherland.

**Comment by originalhat** [comment]
## Post #0...

![screen shot 2013-10-08 at 7 00 41 am](https://f.cloud.github.com/assets/579630/1288964/b16b314c-3019-11e3-8e7c-b12e393a5d38.png)
